apiVersion: apps/v1
kind: Deployment
metadata:
  name: mala-leche
  labels:
    app: mala-leche
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mala-leche
  template:
    metadata:
      labels:
        app: mala-leche
    spec:
      containers:
      - name: mala-leche
        image: elmalba/malaleche
        env:
            - name: PORT
              value: "8000"
        ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mala-leche
  namespace: malba
spec:
  selector:
    app: mala-leche
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: mala-leche
    annotations:
        kubernetes.io/ingress.class: "traefik"
        traefik.frontend.rule.type: PathPrefixStrip
spec:
    rules:
    - host: "online.juegamalaleche.cl"
      http:
        paths:
        - path: /
          backend:
            serviceName: mala-leche
            servicePort: 80