apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: cah
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cah
  template:
    metadata:
      labels:
        app: cah
    spec:
      containers:
      - name: cah
        image: yusufameri/cah:0.1.0
        ports:
        - containerPort: 80
